[package]
name = "keybbboard"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "keybbboard-host"
path = "src/host.rs"

[[bin]]
name = "keybbboard-device"
path = "src/device.rs"

[dependencies]
crossterm = "0.28.1"
